=== cc-chris-cc/WBA2SS13Phase1/bin/aufgabe3/Rezepte.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" targetNamespace="http://example.org/Rezepte"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rezept">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="titel" type="xs:string" />
				
				<xs:element name="fotos" type="xs:anyURI" />
				
				<xs:element name="zutaten">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="zutat" maxOccurs="unbounded"
								minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="bezeichnung" />
										<xs:element type="xs:float" name="menge" />
										<xs:element name="einheit">
											<xs:simpleType>
												<!-- Auswahlmöglichkeiten eingeschränkt durch restriction -->
												<xs:restriction base="xs:string">
													<!-- g = Gramm -->
													<xs:enumeration value="g" />
													<!--  kg = Kilogramm -->
													<xs:enumeration value="kg" />
													<!-- Msp. = Messerspitze -->
													<xs:enumeration value="Msp." />
													<!-- cl = Centiliter -->
													<xs:enumeration value="cl" />
													<!-- ml = Milliliter -->
													<xs:enumeration value="ml" />
													<!-- dl = Deziliter -->
													<xs:enumeration value="dl" />
													<!-- EL = Eßloeffel -->
													<xs:enumeration value="EL" />
													<!-- TL = Teeloeffel -->
													<xs:enumeration value="TL" />
													<!-- Pkt. = Packung -->
													<xs:enumeration value="Pkt." />
													<!-- Ei = Ei(er) -->
													<xs:enumeration value="Ei" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:short" name="id" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="portionen" type="xs:integer" />
				
				<xs:element name="zubereitung">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="arbeitszeit" type="xs:integer" />
							<!-- Einschränkung des Schwierigkeitsgrades -->
							<xs:element name="schwierigkeitsgrad">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="simpel" />
										<xs:enumeration value="mittel" />
										<xs:enumeration value="schwierig" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="brennwertAnzeige">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="menge2" type="xs:positiveInteger" />
										
										<xs:element name="brennwert" type="xs:string"
											fixed="kcal" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="text" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="kommentare">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="eintrag" maxOccurs="unbounded"
								minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="autor" />
										<xs:element type="xs:dateTime" name="datum" />
										<xs:element type="xs:string" name="text" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== cc-chris-cc/WBA2SS13Phase1/bin/aufgabe3/generierteXMLDatei.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<rezept xmlns="http://example.org/Rezepte" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.org/Rezepte Rezepte.xsd">
    <titel>p:titel</titel>
    <fotos>http://tempuri.org</fotos>
    <zutaten>
        <zutat>
            <bezeichnung>p:bezeichnung</bezeichnung>
            <menge>0.0</menge>
            <einheit>g</einheit>
        </zutat>
    </zutaten>
    <portionen>0</portionen>
    <zubereitung>
        <arbeitszeit>0</arbeitszeit>
        <schwierigkeitsgrad>simpel</schwierigkeitsgrad>
        <brennwertAnzeige>
            <menge2>1</menge2>
            <brennwert>kcal</brennwert>
        </brennwertAnzeige>
        <text>p:text</text>
    </zubereitung>
    <kommentare>
        <eintrag>
            <autor>han</autor>
            <datum>2013-04-13T16:01:00.071+02:00</datum>
            <text>sjskjsla</text>
        </eintrag>
        <eintrag>
            <autor>djhvkjsdhkjdhgv</autor>
            <datum>2013-04-13T16:01:46.216+02:00</datum>
            <text>jkhfsdkjxfhsdkjxhkjxhdgkjdxh</text>
        </eintrag>
    </kommentare>
</rezept>

=== cc-chris-cc/WBA2SS13Phase1/bin/aufgabe3/Aufgabe3.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<rezept xmlns="http://example.org/Rezepte" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.org/Rezepte Rezepte.xsd">
    <titel>Lenchen's Schokoladenkuchen</titel>
    <fotos></fotos>
    <zutaten>
        <zutat id="1">
            <bezeichnung>Butter</bezeichnung>
            <menge>200.0</menge>
            <einheit>g</einheit>
        </zutat>
        <zutat id="2">
            <bezeichnung>Zucker</bezeichnung>
            <menge>200.0</menge>
            <einheit>g</einheit>
        </zutat>
        <zutat id="3">
            <bezeichnung>Schokolade, Blockschokolade</bezeichnung>
            <menge>200.0</menge>
            <einheit>g</einheit>
        </zutat>
        <zutat id="4">
            <bezeichnung>Mehl</bezeichnung>
            <menge>120.0</menge>
            <einheit>g</einheit>
        </zutat>
        <zutat id="5">
            <bezeichnung>Backpulver</bezeichnung>
            <menge>0.5</menge>
            <einheit>TL</einheit>
        </zutat>
        <zutat id="6">
            <bezeichnung>Vanillezucker</bezeichnung>
            <menge>1.0</menge>
            <einheit>Pkt.</einheit>
        </zutat>
        <zutat id="7">
            <bezeichnung>Eier</bezeichnung>
            <menge>4.0</menge>
            <einheit>Ei</einheit>
        </zutat>
    </zutaten>
    <portionen>16</portionen>
    <zubereitung>
        <arbeitszeit>60</arbeitszeit>
        <schwierigkeitsgrad>simpel</schwierigkeitsgrad>
        <brennwertAnzeige>
            <menge2>295</menge2>
            <brennwert>kcal</brennwert>
        </brennwertAnzeige>
        <text>Butter und Schokolade im Wasserbad schmelzen. Eier trennen. Eiweiß steif schlagen. Eigelbe, Zucker und Vanillezucker verrühren. Geschmolzene Butter-Schokomasse hinzufügen und mischen. Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben. In eine gut gefettete Form geben. 
Bei 180°Grad 40 – 50 Minuten backen.</text>
    </zubereitung>
    <kommentare>
        <eintrag>
            <autor>swieselchen</autor>
            <datum>2002-02-07T18:49:00</datum>
            <text>Habe Deinen Kuchen gestern gebacken (kleine Abwandlung: statt Blockschokolade hatte ich nur Kuvertüre, zartbitter und ich habe noch etwas Rumaroma und eine Prise Salz dazugegeben) mein LAG war total begeistert. Ich übrigends auch, super Rezept. 
		</text>
        </eintrag>
        <eintrag>
            <autor>thecook</autor>
            <datum>2006-12-07T12:24:00</datum>
            <text>Habe ihn eben gebacken und bin begeistert.Super Rezept:-) 
		</text>
        </eintrag>
        <eintrag>
            <autor>2</autor>
            <datum>2013-04-13T16:14:03.402+02:00</datum>
            <text>hdskjh</text>
        </eintrag>
    </kommentare>
</rezept>
